C언어로 구현된 파이썬 라이브러리
고성능 수치계산을 위해 만들엊ㄴ 파이썬 라이브러리
Vector , matrix , n-th array(ndarray) 등의 데이터 분석을 위한 패키지
벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공

1 차원의 Numpy array : Vector

2 차원의 Numpy array : Matrix

3 차원 이상의 Numpy array : Tensor

numpy 는 Element-wise operation : 각각의 원소에 접근해 연산한다.


# numpy 모듈 선언

In [5]:
import numpy as np

In [6]:
np.__version__

'1.20.1'

# Array 정의 및 사용
- 시퀀스 데이터(리스트, 튜플 등) 으로부터 배열 생성

## array(object , dtype)
형식 : arr_obj = np.array(seq_data)

In [7]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [8]:
data2 = [1,2,3,3.5,5]
data2

[1, 2, 3, 3.5, 5]

In [9]:
# 리스트 객체를 이용하여 array 생성
arr1 = np.array(data1)
arr1

array([1, 2, 3])

## array 크기 확인 : shape
## array 차원 확인 : ndim
## array itemsize 확인 : itemsize
## array 내 element 수 확인 : size

In [10]:
# array 크기 확인
arr1.shape

(3,)

In [11]:
# 리스트를 직접 입력하여 array 생성
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [12]:
arr2.shape

(5,)

In [17]:
arr2.ndim

1

In [23]:
arr2.itemsize # 8bits가 4번 들어감

4

In [24]:
arr2.dtype

dtype('int32')

In [25]:
arr2.size

5

## array 자료형 확인 : dtype

In [17]:
# array의 자료형 확인
arr2.dtype

dtype('int32')

In [21]:
arr3 = np.array([1,2,3,3.5,4])
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [23]:
arr3.dtype

dtype('float64')

In [25]:
arr3.shape

(5,)

In [31]:
arr4 = np.array([[1,2,3,4] , [4,5,6,7] , [7,8,9,10]])
arr4

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [33]:
arr4.shape #큰 괄호가 3개 , 안에 숫자 4개 =>(3,4)

(3, 4)

In [35]:
arr4.dtype

dtype('int32')

# 범위를 지정해 배열 생성(1) : np.arange() 함수
## 형식 : arr_obj = np.arange([start] , stop , step])
arange 는 정수값 , linspace는 실수값

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,5)

array([1, 2, 3, 4])

In [41]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [43]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
b1 = np.arange(12).reshape(3,4)
b1.shape

(3, 4)

In [48]:
b3 = b1.reshape(4,3)
b3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 범위를 지정해 배열 생성(2) : linspace() 함수
### 형식 : arr.obj = np.linspace(start,stop[,num=50])

In [50]:
np.linspace(1,10,10) #뒤에 10은 나눈값

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [53]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [58]:
a = np.linspace(1,10)
a
a.shape
# 갯수는 기본값이 50개

(50,)

## 특별한 형태의 배열 생성
### np.zeros() , np.onjes() , np.eye() 함수

### 1) 모든 요소가 0인 배열 생성 : np.zeros(shape, dtype=float,...)
float이 기본 default 값

In [61]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.zeros((3,5)).reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 모든 요소가 1인 배열 생성 : np.ones(shape, dtype=None)

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.ones((3,5) , dtype=int)  # 위의 값은 실수형으로 출력

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 대각 요소가 1인 배열 생성1 : np.eye(n,m, k=K , dtype=float)

In [68]:
# 3행 3열의 대각요소만 1인 행렬 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.eye(3,4) # 완전 대각은 없기 때문에 만나는 요소의 대각 부분에 생성

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [74]:
np.eye(3,4, k=1 , dtype=int) # k는 오프셋 값이다. 1을 줘서 1칸 옆으로 이동함

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [75]:
np.eye(3,4 , k=2 , dtype = int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [77]:
np.eye(3,4, k= -1 ) # k=-1 : 왼쪽으로 한칸

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### 4) 대각요소가 1인 배열 생성2 : np.identity(n, dtype=자료형)

In [153]:
# n*n 크기의 단위 행렬 생성
np.identity(5 , dtype = int) # 5행 5열

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### 5) 초기화되지 않은 배열 생성 : np.empty(shape, dtype =float)

In [159]:
# 초기화되지 않은 배열 생성 -> 그냥 1차원 생성
np.empty(4)

array([0., 0., 0., 0.])

## 배열의 데이터 타입 변환 : astype() 함수

형식
num_arr = str_arr.astype(dtype)
dtype = int, float , str

In [85]:
np.array(['1.5' , '0.62' , '2' , '3.14' , '3.141592']) #unicode 형태로 출력됨

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [95]:
str_a1 = np.array(['1.5' , '0.62' , '2' , '3.14' , '3.141592'])
# num_a1 = str_a1.astype(float) 으로도 가능

num_a1 = str_a1.astype('float64') 
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [96]:
str_a1.dtype

dtype('<U8')

In [94]:
num_a1.dtype

dtype('float64')

In [100]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [164]:
num_a3 = str_a2.astype(float)
num_a3

array([1., 3., 5., 7., 9.])

In [167]:
num_a4 = str_a1.astype(int)
num_a4
# 문자 형태를 int 형태로 바꿀수없다

ValueError: invalid literal for int() with base 10: '1.5'

## 실수형 배열을 정수형 배열로 변환

In [106]:
num_f1 = np.array([10,21,0,549,4.75,5.98])
num_f1

array([ 10.  ,  21.  ,   0.  , 549.  ,   4.75,   5.98])

In [109]:
num_i1 = num_f1.astype(int)
num_i1 # 정수형으로 바꿈 

array([ 10,  21,   0, 549,   4,   5])

In [110]:
num_f1.dtype

dtype('float64')

In [111]:
num_i1.dtype

dtype('int32')

## 숫자형 배열을 문자열 배열로 변환  

In [112]:
num_f1.astype(str)

array(['10.0', '21.0', '0.0', '549.0', '4.75', '5.98'], dtype='<U32')

In [113]:
num_f1.astype('U') # 문자형

array(['10.0', '21.0', '0.0', '549.0', '4.75', '5.98'], dtype='<U32')

In [114]:
num_f1.astype('S') # 바이트 문자열

array([b'10.0', b'21.0', b'0.0', b'549.0', b'4.75', b'5.98'], dtype='|S32')

## 난수 배열 생성
### random.rand() , random.randint() 함수

#### random.rand([d0,d1,...dn])
- [0과 1) 사이의 실수 난수를 갖는 Numpy 배열을 생성 (0이상 1미만)
- rand(d0, d1 , ...dn)을 실행하면 (d0,d1,....dn)의 형태를 보이는 실수 난수 배열 생성

In [115]:
np.random.rand(10)

array([0.39154575, 0.62794181, 0.26223198, 0.71080874, 0.31405352,
       0.81977727, 0.13258176, 0.53091646, 0.8359852 , 0.42743904])

In [116]:
np.random.rand(2,5)

array([[0.08912011, 0.7532605 , 0.21900251, 0.67275986, 0.25147823],
       [0.76336175, 0.16405505, 0.33936419, 0.01114812, 0.31523143]])

In [117]:
np.random.rand()

0.010843420893074551

In [118]:
np.random.rand(2,3,4)

array([[[0.87661979, 0.15765556, 0.19656916, 0.35328527],
        [0.95959159, 0.01694753, 0.08363133, 0.61699452],
        [0.85018976, 0.16859495, 0.49255428, 0.49381173]],

       [[0.39992064, 0.037971  , 0.1711319 , 0.38797094],
        [0.07182216, 0.64526062, 0.00395433, 0.09848924],
        [0.42322694, 0.23230249, 0.53174579, 0.84005685]]])

## random.randint([low] , high , [,size])
- low, high 사이의 정수 난수를 갖는 Numpy 배열을 생성
- size : (d0,d1,...dn) 형식으로 입력

In [119]:
np.random.randint(10)

8

In [121]:
np.random.randint(10, 20)

15

In [122]:
np.random.randint(10,20, size=(3,4))

array([[18, 13, 19, 17],
       [18, 18, 19, 18],
       [13, 17, 11, 16]])

## Array 연산

### 기본 연산(합, 차 ,곱 , 나눗셈 등)
: 기본적으로 동일한 크기의 array 간 연산 수행

In [126]:
arr1 = np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
arr2 = np.arange(10,16).reshape(2,3)
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [134]:
print(arr1.shape)
print(arr2.shape)

(2, 3)
(2, 3)


## 배열의 합

In [135]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

## 배열의 차

In [136]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

## 배열의 곱

In [137]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

## 배열의 나눗셈

In [138]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

## 배열의 스칼라 곱

In [139]:
arr2*2

array([[20, 22, 24],
       [26, 28, 30]])

## 배열의 비교 연산

In [144]:
arr2>12

array([[False, False, False],
       [ True,  True,  True]])

## 배열의 Broadcasting
- 서로 크기가 다른 array들의 연산이 가능하도록 배열을 자동적으로 변환하여 연산 수행

In [146]:
arr1 = np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [148]:
(arr1.shape , arr3.shape)

((2, 3), (3,))

In [150]:
arr1 + arr3 # 서로 크기가 달라도 연산이 가능하다

array([[11, 13, 15],
       [14, 16, 18]])

In [151]:
arr1 **2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## 브로드캐스팅이 일어날 수 있는 조건
- 두 배열 간의 연산에서 최소한 하나의 배열이 차원이 1인 경우
- 차원의 짝이 맞을 때

## 3차원 행렬 만들기

In [31]:
a = np.array([
    [[10],[20]],
    [[30],[40]]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[[10]
  [20]]

 [[30]
  [40]]]
3
4
(2, 2, 1)


In [34]:
b = np.array([
    [[10,50] , [20,60]],
    [[30,70] , [40,80]]
])
print(b)
print(b.ndim)
print(b.size)
print(b.shape)

[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]
3
8
(2, 2, 2)


## insert / delete

In [40]:
a = np.array([10,20,30])
a = np.insert(a,0,5) #(array , index위치 , 값)
a

array([ 5, 10, 20, 30])

In [44]:
np.delete(a,0) # delete(array , index위치)

array([10, 20, 30])

## Numpy - Math and Logical Operations

In [45]:
a = np.array([10,20,30])
b = np.array([1,2,3])

In [47]:
c=a+b
c

array([11, 22, 33])

In [48]:
c = a-b
c

array([ 9, 18, 27])

In [49]:
c = b**2
c

array([1, 4, 9], dtype=int32)

In [50]:
idx = b<20
idx

array([ True,  True,  True])

## Numpy 함수 이용

### np.add(a,b)
### np.subtract(a,b)
### np.multiply(a,b)
### np.divide(a,b)
### np.divmod(a,b)
### np.exp(b) => e의 b승
### np.sqrt(b) => 제곱근
### np.mean(a) = a.mean() 같은 기능

### np.average(a) => average는 가중치를 줄 수 있다.
### np.average(a,weights = [1,1,1])

In [51]:
a = np.array([10,20,30])
np.average(a)

20.0

In [54]:
np.average(a , weights = [1,1,1])

20.0

In [55]:
np.average(a , weights = [1,1,0])

15.0

In [56]:
np.average(a , weights = [1,0,1])

20.0

## np.median(a) : 중앙값
## np.cumsum(a) : 숫자들의 더해진 값 => array
## np.cov(a) : 공분산 구하기
## np.std(a) : 표준편차 구하기
## np.var(a) : 분산 구하기