C언어로 구현된 파이썬 라이브러리
고성능 수치계산을 위해 만들엊ㄴ 파이썬 라이브러리
Vector , matrix , n-th array(ndarray) 등의 데이터 분석을 위한 패키지
벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공

1 차원의 Numpy array : Vector

2 차원의 Numpy array : Matrix

3 차원 이상의 Numpy array : Tensor

numpy 는 Element-wise operation : 각각의 원소에 접근해 연산한다.


# numpy 모듈 선언

In [3]:
import numpy as np

In [6]:
np.__version__

'1.20.1'

# Array 정의 및 사용
- 시퀀스 데이터(리스트, 튜플 등) 으로부터 배열 생성

## array(object , dtype)
형식 : arr_obj = np.array(seq_data)

In [7]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [8]:
data2 = [1,2,3,3.5,5]
data2

[1, 2, 3, 3.5, 5]

In [9]:
# 리스트 객체를 이용하여 array 생성
arr1 = np.array(data1)
arr1

array([1, 2, 3])

## array 크기 확인 : shape
## array 차원 확인 : ndim
## array itemsize 확인 : itemsize
## array 내 element 수 확인 : size

In [10]:
# array 크기 확인
arr1.shape

(3,)

In [11]:
# 리스트를 직접 입력하여 array 생성
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [12]:
arr2.shape

(5,)

In [17]:
arr2.ndim

1

In [23]:
arr2.itemsize # 8bits가 4번 들어감

4

In [24]:
arr2.dtype

dtype('int32')

In [25]:
arr2.size

5

## array 자료형 확인 : dtype

In [17]:
# array의 자료형 확인
arr2.dtype

dtype('int32')

In [21]:
arr3 = np.array([1,2,3,3.5,4])
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [23]:
arr3.dtype

dtype('float64')

In [25]:
arr3.shape

(5,)

In [31]:
arr4 = np.array([[1,2,3,4] , [4,5,6,7] , [7,8,9,10]])
arr4

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [33]:
arr4.shape #큰 괄호가 3개 , 안에 숫자 4개 =>(3,4)

(3, 4)

In [35]:
arr4.dtype

dtype('int32')

# 범위를 지정해 배열 생성(1) : np.arange() 함수
## 형식 : arr_obj = np.arange([start] , stop , step])
arange 는 정수값 , linspace는 실수값

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,5)

array([1, 2, 3, 4])

In [41]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [43]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
b1 = np.arange(12).reshape(3,4)
b1.shape

(3, 4)

In [48]:
b3 = b1.reshape(4,3)
b3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 범위를 지정해 배열 생성(2) : linspace() 함수
### 형식 : arr.obj = np.linspace(start,stop[,num=50])

In [50]:
np.linspace(1,10,10) #뒤에 10은 나눈값

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [53]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [58]:
a = np.linspace(1,10)
a
a.shape
# 갯수는 기본값이 50개

(50,)

## 특별한 형태의 배열 생성
### np.zeros() , np.ones() , np.eye() 함수

### 1) 모든 요소가 0인 배열 생성 : np.zeros(shape, dtype=float,...)
float이 기본 default 값

In [61]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.zeros((3,5)).reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 모든 요소가 1인 배열 생성 : np.ones(shape, dtype=None)

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.ones((3,5) , dtype=int)  # 위의 값은 실수형으로 출력

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 대각 요소가 1인 배열 생성1 : np.eye(n,m, k=K , dtype=float)

In [68]:
# 3행 3열의 대각요소만 1인 행렬 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.eye(3,4) # 완전 대각은 없기 때문에 만나는 요소의 대각 부분에 생성

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [74]:
np.eye(3,4, k=1 , dtype=int) # k는 오프셋 값이다. 1을 줘서 1칸 옆으로 이동함

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [75]:
np.eye(3,4 , k=2 , dtype = int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [77]:
np.eye(3,4, k= -1 ) # k=-1 : 왼쪽으로 한칸

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### 4) 대각요소가 1인 배열 생성2 : np.identity(n, dtype=자료형)

In [153]:
# n*n 크기의 단위 행렬 생성
np.identity(5 , dtype = int) # 5행 5열

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### 5) 초기화되지 않은 배열 생성 : np.empty(shape, dtype =float)

In [159]:
# 초기화되지 않은 배열 생성 -> 그냥 1차원 생성
np.empty(4)

array([0., 0., 0., 0.])

## 배열의 데이터 타입 변환 : astype() 함수

형식
num_arr = str_arr.astype(dtype)
dtype = int, float , str

In [85]:
np.array(['1.5' , '0.62' , '2' , '3.14' , '3.141592']) #unicode 형태로 출력됨

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [95]:
str_a1 = np.array(['1.5' , '0.62' , '2' , '3.14' , '3.141592'])
# num_a1 = str_a1.astype(float) 으로도 가능

num_a1 = str_a1.astype('float64') 
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [96]:
str_a1.dtype

dtype('<U8')

In [94]:
num_a1.dtype

dtype('float64')

In [100]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [164]:
num_a3 = str_a2.astype(float)
num_a3

array([1., 3., 5., 7., 9.])

In [167]:
num_a4 = str_a1.astype(int)
num_a4
# 문자 형태를 int 형태로 바꿀수없다

ValueError: invalid literal for int() with base 10: '1.5'

## 실수형 배열을 정수형 배열로 변환

In [106]:
num_f1 = np.array([10,21,0,549,4.75,5.98])
num_f1

array([ 10.  ,  21.  ,   0.  , 549.  ,   4.75,   5.98])

In [109]:
num_i1 = num_f1.astype(int)
num_i1 # 정수형으로 바꿈 

array([ 10,  21,   0, 549,   4,   5])

In [110]:
num_f1.dtype

dtype('float64')

In [111]:
num_i1.dtype

dtype('int32')

## 숫자형 배열을 문자열 배열로 변환  

In [112]:
num_f1.astype(str)

array(['10.0', '21.0', '0.0', '549.0', '4.75', '5.98'], dtype='<U32')

In [113]:
num_f1.astype('U') # 문자형

array(['10.0', '21.0', '0.0', '549.0', '4.75', '5.98'], dtype='<U32')

In [114]:
num_f1.astype('S') # 바이트 문자열

array([b'10.0', b'21.0', b'0.0', b'549.0', b'4.75', b'5.98'], dtype='|S32')

## 난수 배열 생성
### random.rand() , random.randint() 함수

#### random.rand([d0,d1,...dn])
- [0과 1) 사이의 실수 난수를 갖는 Numpy 배열을 생성 (0이상 1미만)
- rand(d0, d1 , ...dn)을 실행하면 (d0,d1,....dn)의 형태를 보이는 실수 난수 배열 생성

In [115]:
np.random.rand(10)

array([0.39154575, 0.62794181, 0.26223198, 0.71080874, 0.31405352,
       0.81977727, 0.13258176, 0.53091646, 0.8359852 , 0.42743904])

In [116]:
np.random.rand(2,5)

array([[0.08912011, 0.7532605 , 0.21900251, 0.67275986, 0.25147823],
       [0.76336175, 0.16405505, 0.33936419, 0.01114812, 0.31523143]])

In [117]:
np.random.rand()

0.010843420893074551

In [118]:
np.random.rand(2,3,4)

array([[[0.87661979, 0.15765556, 0.19656916, 0.35328527],
        [0.95959159, 0.01694753, 0.08363133, 0.61699452],
        [0.85018976, 0.16859495, 0.49255428, 0.49381173]],

       [[0.39992064, 0.037971  , 0.1711319 , 0.38797094],
        [0.07182216, 0.64526062, 0.00395433, 0.09848924],
        [0.42322694, 0.23230249, 0.53174579, 0.84005685]]])

## random.randint([low] , high , [,size])
- low, high 사이의 정수 난수를 갖는 Numpy 배열을 생성
- size : (d0,d1,...dn) 형식으로 입력

In [119]:
np.random.randint(10)

8

In [121]:
np.random.randint(10, 20)

15

In [122]:
np.random.randint(10,20, size=(3,4))

array([[18, 13, 19, 17],
       [18, 18, 19, 18],
       [13, 17, 11, 16]])

## Array 연산

### 기본 연산(합, 차 ,곱 , 나눗셈 등)
: 기본적으로 동일한 크기의 array 간 연산 수행

In [126]:
arr1 = np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
arr2 = np.arange(10,16).reshape(2,3)
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [134]:
print(arr1.shape)
print(arr2.shape)

(2, 3)
(2, 3)


## 배열의 합

In [135]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

## 배열의 차

In [136]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

## 배열의 곱

In [137]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

## 배열의 나눗셈

In [138]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

## 배열의 스칼라 곱

In [139]:
arr2*2

array([[20, 22, 24],
       [26, 28, 30]])

## 배열의 비교 연산

In [144]:
arr2>12

array([[False, False, False],
       [ True,  True,  True]])

## 배열의 Broadcasting
- 서로 크기가 다른 array들의 연산이 가능하도록 배열을 자동적으로 변환하여 연산 수행

In [146]:
arr1 = np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [148]:
(arr1.shape , arr3.shape)

((2, 3), (3,))

In [150]:
arr1 + arr3 # 서로 크기가 달라도 연산이 가능하다

array([[11, 13, 15],
       [14, 16, 18]])

In [151]:
arr1 **2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## 브로드캐스팅이 일어날 수 있는 조건
- 두 배열 간의 연산에서 최소한 하나의 배열이 차원이 1인 경우
- 차원의 짝이 맞을 때

## 3차원 행렬 만들기

In [31]:
a = np.array([
    [[10],[20]],
    [[30],[40]]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[[10]
  [20]]

 [[30]
  [40]]]
3
4
(2, 2, 1)


In [34]:
b = np.array([
    [[10,50] , [20,60]],
    [[30,70] , [40,80]]
])
print(b)
print(b.ndim)
print(b.size)
print(b.shape)

[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]
3
8
(2, 2, 2)


## insert / delete

In [40]:
a = np.array([10,20,30])
a = np.insert(a,0,5) #(array , index위치 , 값)
a

array([ 5, 10, 20, 30])

In [44]:
np.delete(a,0) # delete(array , index위치)

array([10, 20, 30])

## Numpy - Math and Logical Operations

In [45]:
a = np.array([10,20,30])
b = np.array([1,2,3])

In [47]:
c=a+b
c

array([11, 22, 33])

In [48]:
c = a-b
c

array([ 9, 18, 27])

In [49]:
c = b**2
c

array([1, 4, 9], dtype=int32)

In [50]:
idx = b<20
idx

array([ True,  True,  True])

## Numpy 함수 이용

### np.add(a,b)
### np.subtract(a,b)
### np.multiply(a,b)
### np.divide(a,b)
### np.divmod(a,b)
### np.exp(b) => e의 b승
### np.sqrt(b) => 제곱근
### np.mean(a) = a.mean() 같은 기능

### np.average(a) => average는 가중치를 줄 수 있다.
### np.average(a,weights = [1,1,1])

In [51]:
a = np.array([10,20,30])
np.average(a)

20.0

In [54]:
np.average(a , weights = [1,1,1])

20.0

In [55]:
np.average(a , weights = [1,1,0])

15.0

In [56]:
np.average(a , weights = [1,0,1])

20.0

## np.median(a) : 중앙값
## np.cumsum(a) : 숫자들의 더해진 값 => array
## np.cov(a) : 공분산 구하기
## np.std(a) : 표준편차 구하기
## np.var(a) : 분산 구하기

# Day2

## 통계를 위한 연산
- 배열의 합, 평균, 표준편차 , 분산 , 최소값 , 최대값 , 누적합 , 누적곱 등

In [8]:
arr1 = np.arange(0,5)
arr1

array([0, 1, 2, 3, 4])

In [10]:
# 합과 (산술)평균 : sum()  /  mean()
[arr1.sum() , arr1.mean()]

[10, 2.0]

In [11]:
# 표준편차와 분산 : std() , var()
[arr1.std() , arr1.var()]

[1.4142135623730951, 2.0]

In [12]:
# 최소값과 최대값 : min() , max()
[arr1.min() , arr1.max()]

[0, 4]

In [13]:
# 누적합 cumsum()
arr1.cumsum()

[array([ 0,  1,  3,  6, 10], dtype=int32)]

In [14]:
# 누적곱 : cumprod()
arr1.cumprod()

array([0, 0, 0, 0, 0], dtype=int32)

## 행렬 연산
- 선형 대수를 위한 행렬(2차원 배열) 연산
- 행렬 곱 , 전치 행렬 , 역행렬 , 행렬식 등
    - 행렬곱 : A.dot(B) 또는 np.dot(A,B)
    - 전치행렬 : A.transpose() or np.transpose(A)
    - 역행렬 : np.linalg.inv(A)
    - 행렬식 : np.linalg.det(A)

In [16]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [18]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

## 행렬 곱
(m x n) X (n x p) => n과 n이 같아야 한다!

결과는 (m x p) 행렬로 나타난다

In [19]:
# 행렬의 곱
A.dot(B)

array([[ 3,  4],
       [ 9, 10]])

In [20]:
# 행렬의 곱 2
np.dot(A,B)

array([[ 3,  4],
       [ 9, 10]])

## 전치행렬 => 행과 열을 바꿈

In [21]:
## 전치행렬
A.transpose()

array([[1, 3],
       [2, 4]])

In [22]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

## 역행렬

In [23]:
# 역행렬
A

array([[1, 2],
       [3, 4]])

In [24]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
# 행렬식 (determinant) => 행렬의 크기를 스칼라값으로 나타낸 것으로 보면 된다
np.linalg.det(A)

-2.0000000000000004

In [30]:
# 행렬 A와 역행렬을 곱한 결과
np.dot(A, np.linalg.inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## Array 인덱싱과 슬라이싱
- 인덱싱 : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
- 슬라이싱 : 범위를 지정해 배열의 원소를 선택하는 것
    -: 슬라이싱은 : 연산자를 주로 사용

### 1차원 배열의 인덱싱
배열명[위치]
- 파이썬의 인덱싱과 동일
- 0번째로 시작함

In [31]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# 0번째 요소
arr1[0]

0

In [33]:
# 3번째 요소
arr1[3]

3

### 배열명[[위치1, 위치2 , 위치n]]

In [35]:
# 1,3,4 위치 : shape => (m , n , p ) => 3차원 자료
# 따라서 arr1 은 1차원 행렬이기에 오류가 발생한다
# 인덱스 [ ] : [ m] => 1차원 / [m,n] => 2차원 / [m,n,p] => 3차원
arr1[1,3,4]
# arr1[1,3,4] => 3차원 배열의 위치 1면 3행 4열 을 나타냄

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [37]:
# 인덱스 [ ] : [ m] => 1차원 / [m,n] => 2차원 / [m,n,p] => 3차원
# 따라서 1 , 3 , 4 위치를 나타내고 싶을 때는 리스트로 나타내야 한다. (여러 인덱스의 요소들을 지정)
arr1[[1,3,4]]

array([1, 3, 4])

## 2차원 배열의 인덱싱

In [41]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr2[2,3] #2행 3열

12

In [43]:
# 0행 0열 값 변경
arr2[0,0] = 90

In [44]:
# 변경된 array
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2차원 배열명[행위치]
: 2차원 배열에서 지정한 행 전체가 선택됨

In [49]:
# 두번째 행(1행) 선택
arr2[1]

array([5, 6, 7, 8])

**2차원배열명[:,열위치]**

: 2차원 배열에서 지정한 열 전체 선택

In [47]:
arr2[,1] 
# 실행되지 않는다.

SyntaxError: invalid syntax (<ipython-input-47-f6024495ec40>, line 1)

In [48]:
# 다음과 같이 실행
# 1열 선택
arr2[:,1]

array([ 2,  6, 10])

**2차원 배열의 특정 행을 지정해서 행 전체를 변경**

In [51]:
# 두번째 행 변경
arr2[1] = np.array([-5,1,10,9])
arr2

array([[90,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

## 배열명[[행위치1,행위치2,,,,,행위치n],[열위치1,열위치2,,,,열위치n]]
: 지정한 위치의 원소를 가져옴

In [52]:
arr2[[0,2],[0,1]]

array([90, 10])

## 배열명[조건]
: 배열에서 조건을 만족하는 원소만 선택

- 10 이상인 원소 선택

In [55]:
# 비교 연산 먼저 수행
arr2>10

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [57]:
# 비교 연산 결과를 인덱스로 지정
arr2[arr2>10]

array([90, 11, 12])

In [62]:
# 짝수인 원소 선택
idx = arr2 %2==0

In [63]:
arr2[idx]

array([90,  2,  4, 10, 10, 12])

### 1차원 배열의 슬라이싱(Slicing)

#### 배열[시작위치:끝위치]
: 시작 위치에서 끝 위치-1에 해당하는 배열의 원소를 반환

In [64]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [67]:
arr1[3:9:2] #[시작:끝:간격]

array([3, 5, 7])

In [68]:
arr1[:9:2]

array([0, 2, 4, 6, 8])

In [69]:
arr1[3::2]

array([3, 5, 7, 9])

In [70]:
arr1[::3]

array([0, 3, 6, 9])

In [71]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [72]:
# 처음부터 원하는 위치까지
arr1[:3]

array([0, 1, 2])

In [73]:
# 시작위치 지정하고 마지막까지
arr1[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
# 모든 원소 반환
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2차원 배열의 슬라이싱
배열[시작위치:행끝위치 , 열시작위치:열끝위치]

In [76]:
arr2

array([[90,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

In [77]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [78]:
arr2[2]

array([ 9, 10, 11, 12])

In [79]:
# 3열의 모든 요소 꺼내기
arr2[:,3]

array([ 4,  9, 12])

In [81]:
# 1~2행 , 1~2열의 요소
arr2[1:3 , 1:3]

array([[ 1, 10],
       [10, 11]])

## 배열[행위치][열시작위치:열끝위치]
: 특정 행을 선택한 후 열을 슬라이싱

In [83]:
arr3 = np.arange(10,100,10).reshape(3,3)
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [84]:
# 1행의 0열과 1열 요소 선택
arr3[1,:2]

array([40, 50])

In [87]:
# 1행의 0열과 1열 요소 선택
# 각각 괄호를 사용하여 위치 지정할 수도 있다!!!!!!
arr3[1][:2]

array([40, 50])

In [89]:
# 인덱싱 예시
arr3[2][1]

80

### 슬라이싱 된 배열에 값을 지정   다시 확인 필요!!!

In [200]:
# 0~1 행 , 1~2열 요소 변경
# arr3[0:1][1:2] 이렇게 하면 값은 안나온다.

# arr3[:2][1:3]는 해당되는 값만 가져오는거다!!!!!!!!!!!
# 이렇게 쓰면 처음에 행으로 범위를 제한 시키고 , 그 범위에서 열을 찾기 때문에 다음과 같은 결과가 나온다
# 공통된 부분으로 생각하자
arr3[0:2][1:3]

array([[40,  4,  1]])

In [153]:
arr3

array([[10,  1,  3],
       [40,  4,  1],
       [70, 80, 90]])

In [196]:
arr3[0:2][1:3] #밑애처럼 써야함
arr3[0:2][:, 1:3] 

array([[1, 3],
       [4, 1]])

In [172]:
# 여러개 가져오려면 다음과 같이 작성!
arr3[0:2 , 1:3]

array([[1, 3],
       [4, 1]])

In [126]:
arr3[:2 , 1:3] = np.array([[1,3],[4,1]])
arr3

array([[10,  1,  3],
       [40,  4,  1],
       [70, 80, 90]])

## Array boolean 인덱싱
- 다차원의 인덱싱을 응용하여 boolean 인덱싱
- boolean 인덱싱을 통해 만들어낸 array를 통해 원하는 행 또는 열의 값만 뽑아냄
- 가리고 싶은 부분은 가리고 원하는 요소만 꺼냄

In [118]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [119]:
# names 크기 확인
names.shape

(8,)

In [130]:
# 8행 4열의 실수 난수 배열 생성
data = np.random.randn(8,4)
data

array([[-0.48079963, -1.1246814 ,  0.46834529,  0.87542116],
       [ 0.97711672, -0.66557839, -0.50577443, -0.04705627],
       [ 1.87040554,  1.67152376,  1.06709766, -0.42029546],
       [ 1.31315492, -0.9506259 ,  0.41996431,  0.32295802],
       [ 1.74133032, -0.13594917,  0.27376001, -0.54163117],
       [ 2.03030155,  0.73523711, -1.00278886,  1.00270979],
       [ 0.99418061, -0.64644231,  1.71898133, -0.04729817],
       [-1.68417355,  0.64776135, -0.74288956,  0.41804479]])

In [131]:
data.shape

(8, 4)

In [129]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_mask_Beomwoo = (names == 'Beomwoo')
names_mask_Beomwoo

array([ True,  True, False, False, False,  True, False,  True])

In [132]:
# 요소가 Beomwoo인 항목의 위치와 같은 행의 자료 가져오기
data[names_mask_Beomwoo, :]
# data[names_mask_Beomwoo] 와 같이 사용 가능

array([[-0.48079963, -1.1246814 ,  0.46834529,  0.87542116],
       [ 0.97711672, -0.66557839, -0.50577443, -0.04705627],
       [ 2.03030155,  0.73523711, -1.00278886,  1.00270979],
       [-1.68417355,  0.64776135, -0.74288956,  0.41804479]])

In [136]:
# 요소가 Kim 인 행의 데이터만 꺼내기
names_mask_Kim = (names == 'Kim')
data[names_mask_Kim]

array([[ 1.87040554,  1.67152376,  1.06709766, -0.42029546]])

In [140]:
# 논리 연산을 응용하여 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names=='Park')] 

array([[ 1.87040554,  1.67152376,  1.06709766, -0.42029546],
       [ 0.99418061, -0.64644231,  1.71898133, -0.04729817]])

In [144]:
# data의 0번째 열에서 0보다 작은 것만 가져오기
data[data[:,0]<0]

array([[-0.48079963, -1.1246814 ,  0.46834529,  0.87542116],
       [-1.68417355,  0.64776135, -0.74288956,  0.41804479]])

In [164]:
# 문제 2 data에서 0번째 열이 0보다 작은 행의 2,3번째 열 데이터 가져오기
data[data[:,0]<0][:,2:4]
data[data[:,0]<0, 2:4]

array([[ 0.46834529,  0.87542116],
       [-0.74288956,  0.41804479]])

## 수학 관련 함수
- 제곱근 , 절대값 , 삼각함수 , 지수로그함수, 반올림함수 등

In [166]:
# 각 성분의 절대값 계산하기
np.abs(data)

array([[0.48079963, 1.1246814 , 0.46834529, 0.87542116],
       [0.97711672, 0.66557839, 0.50577443, 0.04705627],
       [1.87040554, 1.67152376, 1.06709766, 0.42029546],
       [1.31315492, 0.9506259 , 0.41996431, 0.32295802],
       [1.74133032, 0.13594917, 0.27376001, 0.54163117],
       [2.03030155, 0.73523711, 1.00278886, 1.00270979],
       [0.99418061, 0.64644231, 1.71898133, 0.04729817],
       [1.68417355, 0.64776135, 0.74288956, 0.41804479]])

In [169]:
# 각 성분의 제곱근 계산하기 : data**0.5 or sqrt
np.sqrt(abs(data))

array([[0.69339716, 1.06050997, 0.68435757, 0.93563944],
       [0.98849214, 0.81582988, 0.7111782 , 0.21692457],
       [1.36762771, 1.29287423, 1.03300419, 0.64830198],
       [1.14592972, 0.97500046, 0.64804654, 0.56829396],
       [1.31959476, 0.36871286, 0.5232208 , 0.73595596],
       [1.4248865 , 0.85745968, 1.00139346, 1.00135398],
       [0.99708606, 0.80401636, 1.31109928, 0.21748142],
       [1.29775712, 0.80483623, 0.86191041, 0.64656384]])

In [173]:
# 지수함수
# 각 성분을 자연대수 e의 지수로 삼는 값을 계산하기
np.exp(data)

array([[0.61828879, 0.32475592, 1.59734885, 2.39988581],
       [2.65678493, 0.51397616, 0.60303838, 0.95403372],
       [6.49092822, 5.32026845, 2.90693035, 0.65685272],
       [3.71788486, 0.38649904, 1.52190724, 1.38120737],
       [5.70492776, 0.872887  , 1.3148992 , 0.58179846],
       [7.61638274, 2.08597653, 0.3668549 , 2.7256578 ],
       [2.70250904, 0.52390636, 5.57884255, 0.95380296],
       [0.18559776, 1.9112574 , 0.47573726, 1.51898872]])

## 로그함수
- 자연로그 : log()
- 상용로그: log10()
- 밑이 2인 로그 : log2()

In [175]:
# 자연로그
np.log(abs(data))

array([[-7.32304676e-01,  1.17499794e-01, -7.58549460e-01,
        -1.33050186e-01],
       [-2.31491674e-02, -4.07098861e-01, -6.81664493e-01,
        -3.05641122e+00],
       [ 6.26155276e-01,  5.13735643e-01,  6.49424975e-02,
        -8.66797336e-01],
       [ 2.72432578e-01, -5.06346652e-02, -8.67585538e-01,
        -1.13023293e+00],
       [ 5.54649373e-01, -1.99547418e+00, -1.29550345e+00,
        -6.13170005e-01],
       [ 7.08184330e-01, -3.07562237e-01,  2.78498189e-03,
         2.70612972e-03],
       [-5.83638478e-03, -4.36271317e-01,  5.41731863e-01,
        -3.05128374e+00],
       [ 5.21274971e-01, -4.34232936e-01, -2.97207885e-01,
        -8.72166689e-01]])

In [178]:
# 상용로그
np.log10(abs(data))

array([[-3.18035880e-01,  5.10295122e-02, -3.29433845e-01,
        -5.77829614e-02],
       [-1.00535556e-02, -1.76800789e-01, -2.96043128e-01,
        -1.32738253e+00],
       [ 2.71935781e-01,  2.23112555e-01,  2.82041683e-02,
        -3.76445300e-01],
       [ 1.18315965e-01, -2.19903557e-02, -3.76787612e-01,
        -4.90853925e-01],
       [ 2.40881162e-01, -8.66623425e-01, -5.62630000e-01,
        -2.66296350e-01],
       [ 3.07560547e-01, -1.33572582e-01,  1.20950227e-03,
         1.17525721e-03],
       [-2.53470971e-03, -1.89470225e-01,  2.35271159e-01,
        -1.32515569e+00],
       [ 2.26386843e-01, -1.88584968e-01, -1.29075745e-01,
        -3.78777180e-01]])

In [180]:
np.log2(abs(data))

array([[-1.05649232e+00,  1.69516370e-01, -1.09435554e+00,
        -1.91950843e-01],
       [-3.33971890e-02, -5.87319508e-01, -9.83433984e-01,
        -4.40946931e+00],
       [ 9.03351111e-01,  7.41163864e-01,  9.36922191e-02,
        -1.25052422e+00],
       [ 3.93037130e-01, -7.30503803e-02, -1.25166135e+00,
        -1.63058144e+00],
       [ 8.00189900e-01, -2.87886070e+00, -1.86901640e+00,
        -8.84617325e-01],
       [ 1.02169402e+00, -4.43718514e-01,  4.01787956e-03,
         3.90411993e-03],
       [-8.42012338e-03, -6.29406465e-01,  7.81553872e-01,
        -4.40207192e+00],
       [ 7.52040815e-01, -6.26465704e-01, -4.28780342e-01,
        -1.25827056e+00]])

## 각 성분의 부호 계산 : sign()
: + 인 경우 1 , -인 경우는 -1

In [181]:
np.sign(data)

array([[-1., -1.,  1.,  1.],
       [ 1., -1., -1., -1.],
       [ 1.,  1.,  1., -1.],
       [ 1., -1.,  1.,  1.],
       [ 1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.]])

## 반올림 함수
np.floor()

In [182]:
np.floor(data)

array([[-1., -2.,  0.,  0.],
       [ 0., -1., -1., -1.],
       [ 1.,  1.,  1., -1.],
       [ 1., -1.,  0.,  0.],
       [ 1., -1.,  0., -1.],
       [ 2.,  0., -2.,  1.],
       [ 0., -1.,  1., -1.],
       [-2.,  0., -1.,  0.]])

## NaN 여부 확인 

In [185]:
# 각 성분이 NaN인 경우 True, 아닌 경우 False 를 반환
np.isnan(data)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [187]:
# 로그변환한 배열 중 NaN 확인
np.isnan(np.log(data))

<ipython-input-187-93220a73000a>:2: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(data))


array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False,  True],
       [False,  True, False, False],
       [False,  True, False,  True],
       [False, False,  True, False],
       [False,  True, False,  True],
       [ True, False,  True, False]])

## 무한대(inf) 확인

In [190]:
# 각 성분이 무한대인 경우 True, 아닌 경우 False 를 출력
np.inf(data)

TypeError: 'float' object is not callable

## 삼각함수

In [191]:
np.cos(data)

array([[ 0.88662539,  0.43146396,  0.89231646,  0.64067354],
       [ 0.55941479,  0.78655975,  0.87479954,  0.99889306],
       [-0.29514686, -0.10055719,  0.48266814,  0.91296842],
       [ 0.25480052,  0.58117386,  0.91310349,  0.94830077],
       [-0.16970862,  0.99077314,  0.96276117,  0.8568689 ],
       [-0.44350471,  0.74167173,  0.53795346,  0.53802011],
       [ 0.54518997,  0.79823182, -0.14764327,  0.99888165],
       [-0.11313448,  0.7974366 ,  0.73651708,  0.91388445]])

In [192]:
np.tan(data)

array([[-0.52162762, -2.09085871,  0.50588597,  1.19844717],
       [ 1.48170533, -0.78508234, -0.55382409, -0.04709103],
       [-3.23720847, -9.8941833 ,  1.81450414, -0.44692698],
       [ 3.79510077, -1.40023405,  0.44652974,  0.3346755 ],
       [-5.80697833, -0.13679296,  0.28081037, -0.60164907],
       [-2.02088507,  0.90439342, -1.56700273,  1.56672954],
       [ 1.53765213, -0.7546058 , -6.69885394, -0.04733347],
       [ 8.7822886 ,  0.75667801, -0.91840225,  0.44422946]])

In [193]:
np.sin(data)

array([[-0.46248829, -0.90213017,  0.45141038,  0.76781339],
       [ 0.82888787, -0.61751417, -0.48448506, -0.0470389 ],
       [ 0.9554519 ,  0.99493128,  0.87580333, -0.40803022],
       [ 0.96699364, -0.81377942,  0.40772787,  0.31737304],
       [ 0.98549428, -0.13553079,  0.27035333, -0.51553438],
       [ 0.89627204,  0.67076303, -0.84297454,  0.842932  ],
       [ 0.83831253, -0.60235036,  0.98904068, -0.04728053],
       [-0.99357968,  0.60340274, -0.67641894,  0.4059744 ]])

## Sums , products , differences 함수

In [194]:
# 전체 성분의 합을 다 더함
np.sum(data)

9.552309975028882

In [195]:
np.sum(data , axis = 1)
# 같은 행을 기준으로 열의 합을 구한 결과
# [i , :]

array([-0.26171458, -0.24129237,  4.18873151,  1.10545135,  1.33750998,
        2.76545959,  2.01942146, -1.36125697])

In [204]:
np.sum(data , axis = 0) # 행의 합 => 동일한 열의 요소들을 합한 결과(axis=0)
# 같은 열을 갖는 행의 요소들을 합한 결과 (ex: 1열의 합 , 2열의 합)
# [ : ,i] 의 결과

array([ 6.76151649, -0.46875496,  1.69669574,  1.5628527 ])

***평균, 표준편차, 분산**

In [205]:
# 전체 성분의 평균 계산
np.mean(data)

0.29850968671965256

In [208]:
# 행별 평균 계산
np.mean(data,axis=1)

array([-0.06542864, -0.06032309,  1.04718288,  0.27636284,  0.33437749,
        0.6913649 ,  0.50485537, -0.34031424])

In [209]:
# 열별 평균 계산
np.mean(data,axis=0)

array([ 0.84518956, -0.05859437,  0.21208697,  0.19535659])

In [210]:
# 전체 성분의 표준편차 계산
np.std(data)

0.9721340164832069

In [211]:
# 행별 표준편차 계산
np.std(data, axis=1)

array([0.78496217, 0.6405502 , 0.89741105, 0.80672667, 0.86194389,
       1.09107387, 0.91431681, 0.93800674])

In [212]:
# 열별 표준편차 계산
np.std(data ,axis=0)

array([1.20795003, 0.92023475, 0.86730093, 0.52678303])

**최대값,최소값**

In [213]:
# 열방향에서 최소값
np.min(data,axis=0)

array([-1.68417355, -1.1246814 , -1.00278886, -0.54163117])

**최대값 , 최소값 위치 인덱스 : argmax() , argmin()**

In [218]:
data=np.random.randn(15).reshape(5,3)
data

array([[-1.24209861,  1.68727058,  0.73446497],
       [ 0.09183673,  0.64897538, -0.35057747],
       [-0.57684148,  1.41468566,  0.22163523],
       [-0.1272199 , -2.14366547,  0.19828539],
       [-1.38446531, -0.52695322, -1.22141301]])

In [221]:
# 전체 성분의 최소값 , 최대값이 위치한 인덱스를 반환(argmin, argmax)
# 2차원 행렬이지만 1차원처럼 인덱스를 계산해서 부여됨
np.argmax(data)

1

In [222]:
np.max(data)

1.6872705843369404

In [223]:
np.argmin(data)

10

In [224]:
np.min(data)

-2.1436654697769506

In [225]:
# 행방향으로 최대값이 위치한 인덱스 반환
np.argmax(data, axis=1)

array([1, 1, 1, 2, 1], dtype=int64)

**누적합(cumsum) , 누적곱(cumprod)**

In [226]:
np.cumsum(data)

array([-1.24209861,  0.44517197,  1.17963695,  1.27147367,  1.92044906,
        1.56987159,  0.99303011,  2.40771578,  2.62935101,  2.50213111,
        0.35846564,  0.55675103, -0.82771428, -1.3546675 , -2.57608051])

In [227]:
# 열기준 누적합
np.cumsum(data,axis=0)

array([[-1.24209861,  1.68727058,  0.73446497],
       [-1.15026188,  2.33624597,  0.38388751],
       [-1.72710336,  3.75093163,  0.60552274],
       [-1.85432326,  1.60726616,  0.80380813],
       [-3.23878857,  1.08031294, -0.41760488]])

In [228]:
np.cumprod(data)

array([-1.24209861e+00, -2.09575645e+00, -1.53925970e+00, -1.41360574e-01,
       -9.17395328e-02,  3.21618129e-02, -1.85522677e-02, -2.62456272e-02,
       -5.81695571e-03,  7.40032517e-04, -1.58638215e-03, -3.14556400e-04,
        4.35492423e-04, -2.29484133e-04,  2.80294907e-04])

In [229]:
np.cumprod(data,axis=1)

array([[-1.24209861, -2.09575645, -1.5392597 ],
       [ 0.09183673,  0.05959978, -0.02089434],
       [-0.57684148, -0.81604937, -0.18086529],
       [-0.1272199 ,  0.2727169 ,  0.05407578],
       [-1.38446531,  0.72954845, -0.89107997]])

In [231]:
# 전체 성분에 대해서 오름차순으로 정렬
np.sort(data)

array([[-1.24209861,  0.73446497,  1.68727058],
       [-0.35057747,  0.09183673,  0.64897538],
       [-0.57684148,  0.22163523,  1.41468566],
       [-2.14366547, -0.1272199 ,  0.19828539],
       [-1.38446531, -1.22141301, -0.52695322]])

In [234]:
# 전체 성분에 대해서 [::-1]를 적용 : 마지막행부터 정렬

# 내림차순이 아니라 행의 순서가 바뀐 상태로 정렬하는것이다

np.sort(data)[::-1]

array([[-1.38446531, -1.22141301, -0.52695322],
       [-2.14366547, -0.1272199 ,  0.19828539],
       [-0.57684148,  0.22163523,  1.41468566],
       [-0.35057747,  0.09183673,  0.64897538],
       [-1.24209861,  0.73446497,  1.68727058]])

In [237]:
# 열방향으로 오름차순 => 열 단위로 오름차순
np.sort(data , axis=0)

array([[-1.38446531, -2.14366547, -1.22141301],
       [-1.24209861, -0.52695322, -0.35057747],
       [-0.57684148,  0.64897538,  0.19828539],
       [-0.1272199 ,  1.41468566,  0.22163523],
       [ 0.09183673,  1.68727058,  0.73446497]])

In [238]:
# 행방향으로 오름차순 
np.sort(data, axis=1)

array([[-1.24209861,  0.73446497,  1.68727058],
       [-0.35057747,  0.09183673,  0.64897538],
       [-0.57684148,  0.22163523,  1.41468566],
       [-2.14366547, -0.1272199 ,  0.19828539],
       [-1.38446531, -1.22141301, -0.52695322]])

**2개의 array에 적용되는 함수**

In [241]:
data1 = np.random.randn(5,3)
data2 = np.random.randn(5,3)

In [243]:
print(data1)
print(data2)

[[-0.11903755 -0.6479789  -1.4032977 ]
 [ 0.87060038 -1.92358833  1.92927202]
 [-1.92281792 -1.57826989  0.18540859]
 [-0.42392959  1.34317205 -1.06888325]
 [ 0.38260439  1.40525337 -0.67316469]]
[[-2.30951148 -0.72562586 -1.00994351]
 [ 0.03733175  0.76303442  1.30353841]
 [-1.29916335 -0.43589875  1.19180491]
 [ 1.65704078 -0.98327379 -0.03446714]
 [ 0.23837587 -0.01278068 -0.19486968]]


In [244]:
# 두 배열의 합
np.add(data1,data2)

array([[-2.42854904, -1.37360476, -2.41324121],
       [ 0.90793213, -1.1605539 ,  3.23281043],
       [-3.22198126, -2.01416864,  1.3772135 ],
       [ 1.23311118,  0.35989826, -1.10335039],
       [ 0.62098026,  1.39247269, -0.86803438]])

In [248]:
# 두 배열의 차
np.subtract(data1,data2)

array([[ 2.19047393,  0.07764696, -0.39335419],
       [ 0.83326862, -2.68662275,  0.62573362],
       [-0.62365457, -1.14237114, -1.00639632],
       [-2.08097037,  2.32644585, -1.03441611],
       [ 0.14422853,  1.41803405, -0.47829501]])

In [250]:
# 두 배열의 곱
np.multiply(data1,data2)

array([[ 0.2749186 ,  0.47019025,  1.41725141],
       [ 0.03250104, -1.4677641 ,  2.51488017],
       [ 2.49805456,  0.68796587,  0.22097087],
       [-0.70246862, -1.32070588,  0.03684135],
       [ 0.09120366, -0.01796009,  0.13117939]])

In [251]:
# 두 배열의 나눗셈
np.divide(data1,data2)

array([[ 5.15423083e-02,  8.92993124e-01,  1.38948138e+00],
       [ 2.33206403e+01, -2.52097189e+00,  1.48002699e+00],
       [ 1.48004323e+00,  3.62072591e+00,  1.55569580e-01],
       [-2.55835342e-01, -1.36602039e+00,  3.10116612e+01],
       [ 1.60504666e+00, -1.09951381e+02,  3.45443524e+00]])

**최대값 또는 최소값 계산 : maximum() , minimum()**

In [252]:
# 두 배열의 같은 위치를 비교해 최대 또는 최소 구하기
np.maximum(data1 , data2)

array([[-0.11903755, -0.6479789 , -1.00994351],
       [ 0.87060038,  0.76303442,  1.92927202],
       [-1.29916335, -0.43589875,  1.19180491],
       [ 1.65704078,  1.34317205, -0.03446714],
       [ 0.38260439,  1.40525337, -0.19486968]])

In [253]:
np.minimum(data1, data2)

array([[-2.30951148, -0.72562586, -1.4032977 ],
       [ 0.03733175, -1.92358833,  1.30353841],
       [-1.92281792, -1.57826989,  0.18540859],
       [-0.42392959, -0.98327379, -1.06888325],
       [ 0.23837587, -0.01278068, -0.67316469]])

**ptp : 최소와 최대의 차이 (peak to peak)**


**x.sort() : 최소 -> 최대로 정렬(오름차순)**

**x.argsort():정렬된 인덱스찾기**

In [4]:
# np.searchsorted(a,b) -> b를 a 자리에 넣을 때 sort 된 상태로 하는 자리값
a = np.array([10,20,30])
b = np.array([-5,25])
np.searchsorted(a,b)

array([0, 2], dtype=int64)

**np.repeat(a,2) => 숫자를 가져와 반복**

In [6]:
a = np.array([[1,2] , [3,4]])
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [8]:
np.repeat(a,2, axis=0)
# 가로 방향 -> 행을 추가하여 반복

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [10]:
np.repeat(a,2,axis=1)
# 1차원 방향으로 반복

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [12]:
np.repeat(a, [1,2] , axis= 0)
# [1,2] => 첫번째 : 1번 반복 , 두번째 : 2번 반복

array([[1, 2],
       [3, 4],
       [3, 4]])

In [13]:
np.repeat(a,[1,2] , axis=1)


array([[1, 2, 2],
       [3, 4, 4]])

In [29]:
# np.concatenate() : 합치기
a = np.array([[1], [2], [3]])
b = np.array([[4],[5],[6]])

In [30]:
np.concatenate((a,b)) # tuple 형식
# => np.concatenate((a,b), axis=0) 0차원 방향으로 연결하는 것과 같다

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [31]:
np.concatenate((a,b) , axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

**np.hstack: 가로 방향 연결**

**np.vstack : 세로 방향 연결**

In [32]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

**np.hsplit : 가로 방향 나누기**

**np.vsplit : 세로 방향 나누기**

In [34]:
a = np.array([[10.,20.,30.],
             [40.,50.,60.]])

In [36]:
np.hsplit(a,3)

[array([[10.],
        [40.]]),
 array([[20.],
        [50.]]),
 array([[30.],
        [60.]])]

In [37]:
np.vsplit(a,2)

[array([[10., 20., 30.]]), array([[40., 50., 60.]])]

**transpose() : 가로/세로를 바꿈**

In [38]:
a

array([[10., 20., 30.],
       [40., 50., 60.]])

In [39]:
a.transpose()

array([[10., 40.],
       [20., 50.],
       [30., 60.]])

**ravel() : 2차원의 함수를 1차원으로 바꿈**

In [40]:
a.ravel()

array([10., 20., 30., 40., 50., 60.])

In [41]:
a.reshape(-1)

array([10., 20., 30., 40., 50., 60.])

In [43]:
a.ravel(order='c') # c-style : row major : 가로방향 중심

array([10., 20., 30., 40., 50., 60.])

In [45]:
a.ravel(order='f') # f-style : fortran-style : column major 세로방향 중심

array([10., 40., 20., 50., 30., 60.])

In [47]:
# a.flatten() : 한줄로 바꾸기
a.flatten()

array([10., 20., 30., 40., 50., 60.])

In [53]:
# a.squeeze() : 필요한 차원만 남기고 압축
a = np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [54]:
b=a.squeeze()

In [55]:
b

array([1, 2, 3])

In [56]:
# a.ndim : 2 / b.ndim : 1